theme: minima
title: Sebastian's CIS 235 Blog Site
author: Sebastian T. Bach
description: I created this blog site to fulfill an assignment for CIS 235, Web Programming, during the Fall 2022 semester.  This site is © 2022 Sebastian T. Bach
baseurl: /cis-235-blog
